export const UPDATE_CRITERIA = "UPDATE_CRITERIA";
export const UPDATE_QUESTIONS = "UPDATE_QUESTIONS";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const RESET_STATE = "RESET_STATE";

export const AUTH_GOOGLE = "AUTH_GOOGLE";
export const AUTH_GOOGLE_RESULT = "AUTH_GOOGLE_RESULT";
export const AUTH_FAIL = "AUTH_FAIL";
