export const UPDATE_CRITERIA = "UPDATE_CRITERIA";
export const UPDATE_QUESTIONS = "UPDATE_QUESTIONS";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const RESET_STATE = "RESET_STATE";

export const AUTH_FINISHED = "AUTH_FINISHED";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET = "AUTH_RESET";
export const AUTH_FAIL = "AUTH_FAIL";

export const USER_LOAD = "USER_LOAD";
export const USER_UNLOAD = "USER_UNLOAD";
export const USER_FAVORITE = "USER_FAVORITE";
export const USER_UNFAVORITE = "USER_UNFAVORITE";

export const BROWSE_FILTER = "BROWSE_FILTER";
export const BROWSE_SORT = "BROWSE_SORT";

export const COMPARE_VEHICLENUM = "COMPARE_VEHICLENUM";
export const COMPARE_VEHICLEINFO = "COMPARE_VEHICLEINFO";
export const COMPARE_CLEARVEHICLE = "COMPARE_CLEARVEHICLE";
