const vehicleInfo = [
  {
    specs: {
      name: "E-Tron",
      manufacturer: "Audi",
      blurb:
        "Sporting classy looks, a refined riding experience, and adequate range for its segment, the 2020 Audi E-Tron makes family outings a next-level affair.",
      price: 63995,
      range: 204,
      body: "SUV",
      seating: 5,
      horsepower: 355,
      chargeTime: 10,
      battery: 95,
      mpg: 74,
      brakes: "Discs front/rear",
      cargo: 28.5,
      dimensions: [193, 76.2, 65.5],
      weight: 5754,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364072/EV-Finder/audi_etron.png",
    },
    questionnaire: {
      criteria: {
        Price: 3,
        Looks: 8,
        Range: 6,
        "Charging Time": 6,
        Horsepower: 8,
        Seating: 10,
        Luxury: 8,
        "Cargo Capacity": 6,
      },
      questions: [
        [0, 0, 10, 0],
        [7, 7, 8],
        [10, 10, 10],
        [7, 8, 10],
        [0, 0, 10],
        [6, 10],
        [0, 8, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "i3",
      manufacturer: "BMW",
      blurb:
        "The BMW i3 is unique, quirky, and perfect for zipping around the city, bringing with it the trademark BMW prestige and quality.",
      price: 49295,
      range: 126,
      body: "Hatchback",
      seating: 4,
      horsepower: 170,
      charge_time: 4.9,
      battery: 42.2,
      mpg: 31,
      brakes: "Discs front/rear",
      cargo: 15.1,
      dimensions: [158.3, 69.9, 62.9],
      weight: 3276,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364072/EV-Finder/bmw_i3.png",
    },
    questionnaire: {
      criteria: {
        Price: 5,
        Looks: 6,
        Range: 3,
        "Charging Time": 10,
        Horsepower: 4,
        Seating: 7,
        Luxury: 5,
        "Cargo Capacity": 3,
      },
      questions: [
        [0, 10, 0, 0],
        [8, 3, 1],
        [10, 8, 2],
        [7, 7, 5],
        [0, 10, 0],
        [1, 10],
        [6, 0, 10, 5],
      ],
    },
  },
  {
    specs: {
      name: "Bolt",
      manufacturer: "Chevrolet",
      blurb:
        "The practical driver's electric vehicle, the Chevrolet Bolt is all about value, boasting industry-leading range, ride comfort, and interior spaciousness",
      price: 37495,
      range: 259,
      body: "Hatchback",
      seating: 5,
      horsepower: 200,
      charge_time: 8.5,
      battery: 66,
      mpg: 118,
      brakes: "Discs front/rear",
      cargo: 56.6,
      dimensions: [164, 69.5, 62.8],
      weight: 3563,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/chevrolet_bolt.png",
    },
    questionnaire: {
      criteria: {
        Price: 8,
        Looks: 6,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 8,
      },
      questions: [
        [10, 0, 0, 0],
        [10, 8, 4],
        [10, 10, 10],
        [10, 10, 10],
        [0, 10, 0],
        [10, 0],
        [10, 0, 5, 8],
      ],
    },
  },
  {
    specs: {
      name: "Ioniq",
      manufacturer: "Hyundai",
      blurb:
        "As Hyundai's main entry into the electric vehicle contest, the Ioniq gives its competitors a run for their money, with stellar fuel economy, driving ergonomics, and added features.",
      price: 34040,
      range: 170,
      body: "Hatchback",
      seating: 5,
      horsepower: 134,
      charge_time: 6,
      battery: 38.3,
      mpg: 133,
      brakes: "Discs front/rear",
      cargo: 23,
      dimensions: [176, 71.7, 58.1],
      weight: 3371,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/hyundai_ioniq.png",
    },
    questionnaire: {
      criteria: {
        Price: 9,
        Looks: 7,
        Range: 3,
        "Charging Time": 9,
        Horsepower: 4,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 4,
      },
      questions: [
        [10, 0, 0, 0],
        [8, 2, 2],
        [10, 10, 0],
        [8, 8, 6],
        [5, 10, 0],
        [0, 10],
        [7, 0, 3, 3],
      ],
    },
  },
  {
    specs: {
      name: "Kona",
      manufacturer: "Hyundai",
      blurb:
        "If future-facing is your cup of tea, the Hyundai Kona Electric's unique styling makes it a clear choice, especially when also considering its leading range, power, and handling",
      price: 38365,
      range: 258,
      body: "SUV",
      seating: 5,
      horsepower: 201,
      charge_time: 9,
      battery: 64,
      mpg: 120,
      brakes: "Discs front/rear",
      cargo: 45.8,
      dimensions: [164.6, 70.9, 61.2],
      weight: 3715,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/hyundai_kona.png",
    },
    questionnaire: {
      criteria: {
        Price: 8,
        Looks: 7,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 9,
        Luxury: 4,
        "Cargo Capacity": 7,
      },
      questions: [
        [10, 0, 0, 0],
        [8, 8, 4],
        [10, 10, 10],
        [8, 8, 9],
        [0, 0, 10],
        [9, 0],
        [8, 5, 3, 7],
      ],
    },
  },
  {
    specs: {
      name: "I-Pace",
      manufacturer: "Jaguar",
      blurb:
        "Nothing else drives like a Jaguar, and with the British carmaker's first entry into the electric vehicle market, this sporty, luxurious SUV is sure to turn heads and tear up the streets.",
      price: 71000,
      range: 234,
      body: "SUV",
      seating: 5,
      horsepower: 394,
      charge_time: 13,
      battery: 90,
      mpg: 76,
      brakes: "Discs front/rear",
      cargo: 52,
      dimensions: [184.3, 74.6, 61.3],
      weight: 4784,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/jaguar_ipace.png",
    },
    questionnaire: {
      criteria: {
        Price: 3,
        Looks: 9,
        Range: 7,
        "Charging Time": 4,
        Horsepower: 8,
        Seating: 7,
        Luxury: 8,
        "Cargo Capacity": 8,
      },
      questions: [
        [0, 0, 10, 0],
        [5, 7, 8],
        [10, 10, 10],
        [7, 8, 8],
        [0, 0, 10],
        [10, 0],
        [0, 8, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "Niro",
      manufacturer: "KIA",
      blurb:
        "Modern KIAs are hard to beat for value, and the Niro EV is no exception, with its mind-boggling range, industry-leading safety features, and planted and responsive handling.",
      price: 40210,
      range: 239,
      body: "SUV",
      seating: 5,
      horsepower: 201,
      charge_time: 9,
      battery: 64,
      mpg: 112,
      brakes: "Discs front/rear",
      cargo: 53,
      dimensions: [171.5, 71.1, 61.4],
      weight: 3854,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/kia_niro.png",
    },
    questionnaire: {
      criteria: {
        Price: 8,
        Looks: 7,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 9,
        Luxury: 4,
        "Cargo Capacity": 7,
      },
      questions: [
        [0, 10, 0, 0],
        [8, 8, 4],
        [10, 10, 10],
        [8, 8, 9],
        [0, 0, 10],
        [9, 0],
        [8, 5, 2, 7],
      ],
    },
  },
  {
    specs: {
      name: "Leaf",
      manufacturer: "Nissan",
      blurb:
        "The grandma of all electric vehicles, the Nissan Leaf is still going strong, built with the simplicity and common sense all new EVs can only hope to emulate.",
      price: 35115,
      range: 150,
      body: "Hatchback",
      seating: 5,
      horsepower: 147,
      charge_time: 8,
      battery: 40,
      mpg: 111,
      brakes: "Discs front/rear",
      cargo: 30,
      dimensions: [176.4, 70.5, 61.6],
      weight: 3569,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/nissan_leaf.png",
    },
    questionnaire: {
      criteria: {
        Price: 9,
        Looks: 6,
        Range: 5,
        "Charging Time": 7,
        Horsepower: 3,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 4,
      },
      questions: [
        [10, 0, 0, 0],
        [9, 3, 2],
        [10, 10, 10],
        [10, 10, 8],
        [0, 10, 0],
        [0, 10],
        [8, 0, 5, 5],
      ],
    },
  },
  {
    specs: {
      name: "Leaf Plus",
      manufacturer: "Nissan",
      blurb:
        "With a torquier engine and greater range than its very capable little brother, the Nissan Leaf Plus quietly gets you where you need to go, and back again.",
      price: 40675,
      range: 226,
      body: "Hatchback",
      seating: 5,
      horsepower: 214,
      charge_time: 9.5,
      battery: 62,
      mpg: 104,
      brakes: "Discs front/rear",
      cargo: 30,
      dimensions: [176.4, 70.5, 61.6],
      weight: 3909,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/nissan_leafplus.png",
    },
    questionnaire: {
      criteria: {
        Price: 7,
        Looks: 6,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 4,
      },
      questions: [
        [0, 10, 0, 0],
        [9, 7, 2],
        [10, 10, 10],
        [10, 10, 9],
        [0, 10, 0],
        [0, 10],
        [8, 0, 5, 5],
      ],
    },
  },
  {
    specs: {
      name: "Taycan",
      manufacturer: "Porsche",
      blurb:
        "The Porsche Taycan marks the Italian sports car manufacturer's bold entry into the electric vehicle market, and with a roaring 522 horsepower and the classic Porsche refinement, the Taycan is sure to give its competitors a run for their money.",
      price: 105150,
      range: 201,
      body: "Coupe",
      seating: 4,
      horsepower: 522,
      charge_time: 9,
      battery: 79.2,
      mpg: 69,
      brakes: "Discs front/rear",
      cargo: 12.9,
      dimensions: [195.4, 77.5, 54.3],
      weight: 4777,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/porsche_taycan.png",
    },
    questionnaire: {
      criteria: {
        Price: 1,
        Looks: 10,
        Range: 6,
        "Charging Time": 7,
        Horsepower: 9,
        Seating: 2,
        Luxury: 10,
        "Cargo Capacity": 2,
      },
      questions: [
        [0, 0, 0, 10],
        [3, 4, 10],
        [10, 10, 10],
        [10, 10, 1],
        [10, 0, 0],
        [0, 10],
        [0, 10, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "Model 3",
      manufacturer: "Tesla",
      blurb:
        "The standard to which all other mid-price electric vehicles are compared, the Tesla Model 3 leads in virtually every category, from range and power to comfort and technology.",
      price: 48190,
      range: 322,
      body: "Sedan",
      seating: 5,
      horsepower: 346,
      charge_time: 6,
      battery: 80.5,
      mpg: 121,
      brakes: "Discs front/rear",
      cargo: 15,
      dimensions: [184.9, 72.8, 56.8],
      weight: 4072,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_model3.png",
    },
    questionnaire: {
      criteria: {
        Price: 5,
        Looks: 7,
        Range: 9,
        "Charging Time": 10,
        Horsepower: 8,
        Seating: 10,
        Luxury: 7,
        "Cargo Capacity": 3,
      },
      questions: [
        [0, 10, 0, 0],
        [9, 9, 7],
        [10, 10, 10],
        [9, 9, 9],
        [10, 0, 0],
        [0, 10],
        [8, 7, 0, 7],
      ],
    },
  },
  {
    specs: {
      name: "Model S",
      manufacturer: "Tesla",
      blurb:
        "The Tesla Model S is the bar to which every aspiring premium electric vehicle must compare itself, boasting a whopping 391 mile range on a single charge, 483 horses of quiet power, and the refinement we've all come to expect from the EV pioneer.",
      price: 70620,
      range: 391,
      body: "Sedan",
      seating: 5,
      horsepower: 483,
      charge_time: 6.5,
      battery: 100,
      mpg: 117,
      brakes: "Discs front/rear",
      cargo: 26.3,
      dimensions: [196, 77.3, 56.9],
      weight: 4883,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_models.png",
    },
    questionnaire: {
      criteria: {
        Price: 3,
        Looks: 9,
        Range: 10,
        "Charging Time": 10,
        Horsepower: 9,
        Seating: 9,
        Luxury: 10,
        "Cargo Capacity": 4,
      },
      questions: [
        [0, 0, 10, 0],
        [8, 8, 10],
        [10, 10, 10],
        [9, 9, 9],
        [10, 0, 0],
        [5, 10],
        [5, 9, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "Model X",
      manufacturer: "Tesla",
      blurb:
        "With its gull-wing doors and sleek, imposing appearance, the Tesla Model X brings the SUV form factor into a whole new, electric generation.",
      price: 101190,
      range: 305,
      body: "SUV",
      seating: 7,
      horsepower: 680,
      charge_time: 6.5,
      battery: 100,
      mpg: 90,
      brakes: "Discs front/rear",
      cargo: 81.2,
      dimensions: [198.3, 78.7, 66],
      weight: 5531,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_modelx.png",
    },
    questionnaire: {
      criteria: {
        Price: 1,
        Looks: 7,
        Range: 10,
        "Charging Time": 10,
        Horsepower: 9,
        Seating: 9,
        Luxury: 9,
        "Cargo Capacity": 10,
      },
      questions: [
        [0, 0, 0, 10],
        [6, 7, 10],
        [10, 10, 10],
        [3, 4, 9],
        [0, 0, 10],
        [10, 0],
        [2, 8, 3, 4],
      ],
    },
  },
  {
    specs: {
      name: "Model Y",
      manufacturer: "Tesla",
      blurb:
        "The Tesla Model Y, not to be outdone by its older sibling the Model X, trades power for comfort and practicality, maintaining Tesla's unique look while at the same time squeezing in class-leading range and comfort into a more attractive value proposition.",
      price: 51190,
      range: 316,
      body: "SUV",
      seating: 5,
      horsepower: 346,
      charge_time: 6,
      battery: 80.5,
      mpg: 121,
      brakes: "Discs front/rear",
      cargo: 68,
      dimensions: [187, 75.6, 63.9],
      weight: 4416,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_modely.png",
    },
    questionnaire: {
      criteria: {
        Price: 5,
        Looks: 7,
        Range: 9,
        "Charging Time": 10,
        Horsepower: 8,
        Seating: 10,
        Luxury: 7,
        "Cargo Capacity": 9,
      },
      questions: [
        [0, 10, 0, 0],
        [8, 8, 8],
        [10, 10, 10],
        [6, 7, 9],
        [0, 0, 10],
        [10, 0],
        [7, 7, 0, 5],
      ],
    },
  },
  {
    specs: {
      name: "E-Golf",
      manufacturer: "Volkswagen",
      blurb:
        "The German manufacturer's first foray into the electric vehicle market, the E-Golf offers all the styling and performance cues we've come to expect from a modern Golf, but in a vastly more eco-friendly variant.",
      price: 33285,
      range: 144.8,
      body: "Hatchback",
      seating: 5,
      horsepower: 134.1,
      charge_time: 9.5,
      battery: 35.8,
      mpg: 113,
      brakes: "Discs front/rear",
      cargo: 43.47,
      dimensions: [168.1, 70.8, 58.3],
      weight: 3560,
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/volkswagen_egolf.png",
    },
    questionnaire: {
      criteria: {
        Price: 10,
        Looks: 7,
        Range: 5,
        "Charging Time": 6,
        Horsepower: 3,
        Seating: 7,
        Luxury: 3,
        "Cargo Capacity": 5,
      },
      questions: [
        [10, 0, 0, 0],
        [9, 3, 2],
        [10, 10, 8],
        [9, 9, 6],
        [0, 10, 0],
        [0, 10],
        [8, 0, 4, 5],
      ],
    },
  },
];

export default vehicleInfo;
