const vehicleInfo = [
  {
    specs: {
      name: "E-Tron",
      manufacturer: "Audi",
      blurb:
        "Sporting classy looks, a refined riding experience, and adequate range for its segment, the 2020 Audi E-Tron makes family outings a next-level affair.",
      price: "$63,995",
      range: "204 miles",
      "body type": "SUV",
      "seat capacity": "5",
      horsepower: "355 hp",
      "charging time": "10.0 hours",
      battery: "95.0 kWh",
      "fuel economy": "74 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "28.5 cu ft",
      dimensions: "193 x 76.2 x 65.5 in",
      weight: "5754 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364072/EV-Finder/audi_etron.png",
    },
    questionnaire: {
      criteria: {
        Price: 3,
        Looks: 8,
        Range: 6,
        "Charging Time": 6,
        Horsepower: 8,
        Seating: 10,
        Luxury: 8,
        "Cargo Capacity": 6,
      },
      questions: [
        [0, 0, 10, 0],
        [7, 7, 8],
        [10, 10, 10],
        [7, 8, 10],
        [0, 0, 10],
        [6, 10],
        [0, 8, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "i3",
      manufacturer: "BMW",
      blurb:
        "The BMW i3 is unique, quirky, and perfect for zipping around the city, bringing with it the trademark BMW prestige and quality.",
      price: "$49,295",
      range: "126 miles",
      "body type": "Hatchback",
      "seat capacity": "4",
      horsepower: "170 hp",
      "charging time": "4.9 hours",
      battery: "42.2 kWh",
      "fuel economy": "31 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "15.1 cu ft",
      dimensions: "158.3 x 69.9 x 62.9 in",
      weight: "3276 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364072/EV-Finder/bmw_i3.png",
    },
    questionnaire: {
      criteria: {
        Price: 5,
        Looks: 6,
        Range: 3,
        "Charging Time": 10,
        Horsepower: 4,
        Seating: 7,
        Luxury: 5,
        "Cargo Capacity": 3,
      },
      questions: [
        [0, 10, 0, 0],
        [8, 3, 1],
        [10, 8, 2],
        [7, 7, 5],
        [0, 10, 0],
        [1, 10],
        [6, 0, 10, 5],
      ],
    },
  },
  {
    specs: {
      name: "Bolt",
      manufacturer: "Chevrolet",
      blurb:
        "The practical driver's electric vehicle, the Chevrolet Bolt is all about value, boasting industry-leading range, ride comfort, and interior spaciousness",
      price: "$37,495",
      range: "259 miles",
      "body type": "Hatchback",
      "seat capacity": "5",
      horsepower: "200 hp",
      "charging time": "8.5 hours",
      battery: "66.0 kWh",
      "fuel economy": "118 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "56.6 cu ft",
      dimensions: "164 x 69.5 x 62.8 in",
      weight: "3563 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/chevrolet_bolt.png",
    },
    questionnaire: {
      criteria: {
        Price: 8,
        Looks: 6,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 8,
      },
      questions: [
        [10, 0, 0, 0],
        [10, 8, 4],
        [10, 10, 10],
        [10, 10, 10],
        [0, 10, 0],
        [10, 0],
        [10, 0, 5, 8],
      ],
    },
  },
  {
    specs: {
      name: "Ioniq",
      manufacturer: "Hyundai",
      blurb:
        "As Hyundai's main entry into the electric vehicle contest, the Ioniq gives its competitors a run for their money, with stellar fuel economy, driving ergonomics, and added features.",
      price: "$34,040",
      range: "170 miles",
      "body type": "Hatchback",
      "seat capacity": "5",
      horsepower: "134 hp",
      "charging time": "6.0 hours",
      battery: "38.3 kWh",
      "fuel economy": "133 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "23.0 cu ft",
      dimensions: "176 x 71.7 x 58.1 in",
      weight: "3371 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/hyundai_ioniq.png",
    },
    questionnaire: {
      criteria: {
        Price: 9,
        Looks: 7,
        Range: 3,
        "Charging Time": 9,
        Horsepower: 4,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 4,
      },
      questions: [
        [10, 0, 0, 0],
        [8, 2, 2],
        [10, 10, 0],
        [8, 8, 6],
        [5, 10, 0],
        [0, 10],
        [7, 0, 3, 3],
      ],
    },
  },
  {
    specs: {
      name: "Kona",
      manufacturer: "Hyundai",
      blurb:
        "If future-facing is your cup of tea, the Hyundai Kona Electric's unique styling makes it a clear choice, especially when also considering its leading range, power, and handling",
      price: "$38,365",
      range: "258 miles",
      "body type": "SUV",
      "seat capacity": "5",
      horsepower: "201 hp",
      "charging time": "9.0 hours",
      battery: "64.0 kWh",
      "fuel economy": "120 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "45.8 cu ft",
      dimensions: "164.6 x 70.9 x 61.2 in",
      weight: "3715 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/hyundai_kona.png",
    },
    questionnaire: {
      criteria: {
        Price: 8,
        Looks: 7,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 9,
        Luxury: 4,
        "Cargo Capacity": 7,
      },
      questions: [
        [10, 0, 0, 0],
        [8, 8, 4],
        [10, 10, 10],
        [8, 8, 9],
        [0, 0, 10],
        [9, 0],
        [8, 5, 3, 7],
      ],
    },
  },
  {
    specs: {
      name: "I-Pace",
      manufacturer: "Jaguar",
      blurb:
        "Nothing else drives like a Jaguar, and with the British carmaker's first entry into the electric vehicle market, this sporty, luxurious SUV is sure to turn heads and tear up the streets.",
      price: "$71,000",
      range: "234 miles",
      "body type": "SUV",
      "seat capacity": "5",
      horsepower: "394 hp",
      "charging time": "13.0 hours",
      battery: "90.0 kWh",
      "fuel economy": "76 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "52.0 cu ft",
      dimensions: "184.3 x 74.6 x 61.3 in",
      weight: "4784 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/jaguar_ipace.png",
    },
    questionnaire: {
      criteria: {
        Price: 3,
        Looks: 9,
        Range: 7,
        "Charging Time": 4,
        Horsepower: 8,
        Seating: 7,
        Luxury: 8,
        "Cargo Capacity": 8,
      },
      questions: [
        [0, 0, 10, 0],
        [5, 7, 8],
        [10, 10, 10],
        [7, 8, 8],
        [0, 0, 10],
        [10, 0],
        [0, 8, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "Niro",
      manufacturer: "KIA",
      blurb:
        "Modern KIAs are hard to beat for value, and the Niro EV is no exception, with its mind-boggling range, industry-leading safety features, and planted and responsive handling.",
      price: "$40,210",
      range: "239 miles",
      "body type": "SUV",
      "seat capacity": "5",
      horsepower: "201 hp",
      "charging time": "9.0 hours",
      battery: "64.0 kWh",
      "fuel economy": "112 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "53.0 cu ft",
      dimensions: "171.5 x 71.1 x 61.4 in",
      weight: "3854 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/kia_niro.png",
    },
    questionnaire: {
      criteria: {
        Price: 8,
        Looks: 7,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 9,
        Luxury: 4,
        "Cargo Capacity": 7,
      },
      questions: [
        [0, 10, 0, 0],
        [8, 8, 4],
        [10, 10, 10],
        [8, 8, 9],
        [0, 0, 10],
        [9, 0],
        [8, 5, 2, 7],
      ],
    },
  },
  {
    specs: {
      name: "Leaf",
      manufacturer: "Nissan",
      blurb:
        "The grandma of all electric vehicles, the Nissan Leaf is still going strong, built with the simplicity and common sense all new EVs can only hope to emulate.",
      price: "$35,115",
      range: "150 miles",
      "body type": "Hatchback",
      "seat capacity": "5",
      horsepower: "147 hp",
      "charging time": "8.0 hours",
      battery: "40.0 kWh",
      "fuel economy": "111 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "30.0 cu ft",
      dimensions: "176.4 x 70.5 x 61.6 in",
      weight: "3569 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364073/EV-Finder/nissan_leaf.png",
    },
    questionnaire: {
      criteria: {
        Price: 9,
        Looks: 6,
        Range: 5,
        "Charging Time": 7,
        Horsepower: 3,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 4,
      },
      questions: [
        [10, 0, 0, 0],
        [9, 3, 2],
        [10, 10, 10],
        [10, 10, 8],
        [0, 10, 0],
        [0, 10],
        [8, 0, 5, 5],
      ],
    },
  },
  {
    specs: {
      name: "Leaf Plus",
      manufacturer: "Nissan",
      blurb:
        "With a torquier engine and greater range than its very capable little brother, the Nissan Leaf Plus quietly gets you where you need to go, and back again.",
      price: "$40,675",
      range: "226 miles",
      "body type": "Hatchback",
      "seat capacity": "5",
      horsepower: "214 hp",
      "charging time": "9.5 hours",
      battery: "62.0 kWh",
      "fuel economy": "104 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "30.0 cu ft",
      dimensions: "176.4 x 70.5 x 61.6 in",
      weight: "3909 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/nissan_leafplus.png",
    },
    questionnaire: {
      criteria: {
        Price: 7,
        Looks: 6,
        Range: 7,
        "Charging Time": 7,
        Horsepower: 6,
        Seating: 8,
        Luxury: 2,
        "Cargo Capacity": 4,
      },
      questions: [
        [0, 10, 0, 0],
        [9, 7, 2],
        [10, 10, 10],
        [10, 10, 9],
        [0, 10, 0],
        [0, 10],
        [8, 0, 5, 5],
      ],
    },
  },
  {
    specs: {
      name: "Taycan",
      manufacturer: "Porsche",
      blurb:
        "The Porsche Taycan marks the Italian sports car manufacturer's bold entry into the electric vehicle market, and with a roaring 522 horsepower and the classic Porsche refinement, the Taycan is sure to give its competitors a run for their money.",
      price: "$105,150",
      range: "201 miles",
      "body type": "Coupe",
      "seat capacity": "4",
      horsepower: "522 hp",
      "charging time": "9.0 hours",
      battery: "79.2 kWh",
      "fuel economy": "69 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "12.9 cu ft",
      dimensions: "195.4 x 77.5 x 54.3 in",
      weight: "4777 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/porsche_taycan.png",
    },
    questionnaire: {
      criteria: {
        Price: 1,
        Looks: 10,
        Range: 6,
        "Charging Time": 7,
        Horsepower: 9,
        Seating: 2,
        Luxury: 10,
        "Cargo Capacity": 2,
      },
      questions: [
        [0, 0, 0, 10],
        [3, 4, 10],
        [10, 10, 10],
        [10, 10, 1],
        [10, 0, 0],
        [0, 10],
        [0, 10, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "Model 3",
      manufacturer: "Tesla",
      blurb:
        "The standard to which all other mid-price electric vehicles are compared, the Tesla Model 3 leads in virtually every category, from range and power to comfort and technology.",
      price: "$48,190",
      range: "322 miles",
      "body type": "Sedan",
      "seat capacity": "5",
      horsepower: "346 hp",
      "charging time": "6.0 hours",
      battery: "80.5 kWh",
      "fuel economy": "121 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "15.0 cu ft",
      dimensions: "184.9 x 72.8 x 56.8 in",
      weight: "4072 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_model3.png",
    },
    questionnaire: {
      criteria: {
        Price: 5,
        Looks: 7,
        Range: 9,
        "Charging Time": 10,
        Horsepower: 8,
        Seating: 10,
        Luxury: 7,
        "Cargo Capacity": 3,
      },
      questions: [
        [0, 10, 0, 0],
        [9, 9, 7],
        [10, 10, 10],
        [9, 9, 9],
        [10, 0, 0],
        [0, 10],
        [8, 7, 0, 7],
      ],
    },
  },
  {
    specs: {
      name: "Model S",
      manufacturer: "Tesla",
      blurb:
        "The Tesla Model S is the bar to which every aspiring premium electric vehicle must compare itself, boasting a whopping 391 mile range on a single charge, 483 horses of quiet power, and the refinement we've all come to expect from the EV pioneer.",
      price: "$70,620",
      range: "391 miles",
      "body type": "Sedan",
      "seat capacity": "5",
      horsepower: "483 hp",
      "charging time": "6.5 hours",
      battery: "100.0 kWh",
      "fuel economy": "117 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "26.3 cu ft",
      dimensions: "196 x 77.3 x 56.9 in",
      weight: "4883 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_models.png",
    },
    questionnaire: {
      criteria: {
        Price: 3,
        Looks: 9,
        Range: 10,
        "Charging Time": 10,
        Horsepower: 9,
        Seating: 9,
        Luxury: 10,
        "Cargo Capacity": 4,
      },
      questions: [
        [0, 0, 10, 0],
        [8, 8, 10],
        [10, 10, 10],
        [9, 9, 9],
        [10, 0, 0],
        [5, 10],
        [5, 9, 0, 0],
      ],
    },
  },
  {
    specs: {
      name: "Model X",
      manufacturer: "Tesla",
      blurb:
        "With its gull-wing doors and sleek, imposing appearance, the Tesla Model X brings the SUV form factor into a whole new, electric generation.",
      price: "$101,190",
      range: "305 miles",
      "body type": "SUV",
      "seat capacity": "7",
      horsepower: "680 hp",
      "charging time": "6.5 hours",
      battery: "100.0 kWh",
      "fuel economy": "90 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "81.2 cu ft",
      dimensions: "198.3 x 78.7 x 66 in",
      weight: "5531 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_modelx.png",
    },
    questionnaire: {
      criteria: {
        Price: 1,
        Looks: 7,
        Range: 10,
        "Charging Time": 10,
        Horsepower: 9,
        Seating: 9,
        Luxury: 9,
        "Cargo Capacity": 10,
      },
      questions: [
        [0, 0, 0, 10],
        [6, 7, 10],
        [10, 10, 10],
        [3, 4, 9],
        [0, 0, 10],
        [10, 0],
        [2, 8, 3, 4],
      ],
    },
  },
  {
    specs: {
      name: "Model Y",
      manufacturer: "Tesla",
      blurb:
        "The Tesla Model Y, not to be outdone by its older sibling the Model X, trades power for comfort and practicality, maintaining Tesla's unique look while at the same time squeezing in class-leading range and comfort into a more attractive value proposition.",
      price: "$51,190",
      range: "316 miles",
      "body type": "SUV",
      "seat capacity": "5",
      horsepower: "346 hp",
      "charging time": "6.0 hours",
      battery: "80.5 kWh",
      "fuel economy": "121 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "68.0 cu ft",
      dimensions: "187 x 75.6 x 63.9",
      weight: "4416 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/tesla_modely.png",
    },
    questionnaire: {
      criteria: {
        Price: 5,
        Looks: 7,
        Range: 9,
        "Charging Time": 10,
        Horsepower: 8,
        Seating: 10,
        Luxury: 7,
        "Cargo Capacity": 9,
      },
      questions: [
        [0, 10, 0, 0],
        [8, 8, 8],
        [10, 10, 10],
        [6, 7, 9],
        [0, 0, 10],
        [10, 0],
        [7, 7, 0, 5],
      ],
    },
  },
  {
    specs: {
      name: "E-Golf",
      manufacturer: "Volkswagen",
      blurb:
        "The German manufacturer's first foray into the electric vehicle market, the E-Golf offers all the styling and performance cues we've come to expect from a modern Golf, but in a vastly more eco-friendly variant.",
      price: "$33,285",
      range: "144.8 miles",
      "body type": "Hatchback",
      "seat capacity": "5",
      horsepower: "134.1 hp",
      "charging time": "9.5 hours",
      battery: "35.8 kWh",
      "fuel economy": "113 MPGe",
      brakes: "Discs front/rear",
      "cargo capacity": "43.47 cu ft",
      dimensions: "168.1 x 70.8 x 58.3",
      weight: "3560 lbs",
      photo:
        "https://res.cloudinary.com/dphmoqr9f/image/upload/v1619364074/EV-Finder/volkswagen_egolf.png",
    },
    questionnaire: {
      criteria: {
        Price: 10,
        Looks: 7,
        Range: 5,
        "Charging Time": 6,
        Horsepower: 3,
        Seating: 7,
        Luxury: 3,
        "Cargo Capacity": 5,
      },
      questions: [
        [10, 0, 0, 0],
        [9, 3, 2],
        [10, 10, 8],
        [9, 9, 6],
        [0, 10, 0],
        [0, 10],
        [8, 0, 4, 5],
      ],
    },
  },
];

export default vehicleInfo;
